### PR TITLE
adds new service account types. closes #193

### LINKED ISSUE #193: update serviceAccount types to include the Complete Kubernetes Integration and Kubernetes Connector
### Description

when creating a Service Account in wiz there are now 6 options - while this provider only supports 4. I'd like to add support for the two latest options:
 - Kubernetes Connector
 - Complete Kubernetes Integration

so that any service account needed can be managed in terraform. I believe this is managed by adding the options to the enums

### Potential Provider Configuration

```go

var ServiceAccountType = []string{
	"THIRD_PARTY",
	"SENSOR",
	"KUBERNETES_ADMISSION_CONTROLLER",
	"BROKER",
   +   "KUBERNETES_CONNECTOR",
   +   "FIRST_PARTY",
}

```

### References

[new service account types to be added eventually](https://github.com/AxtonGrams/terraform-provider-wiz/issues/152#issuecomment-1655672889)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by mjuarez**
Adds new service account types

### CODE REVIEW

**Comment by jschoombee** [comment]
Thanks for contribution

**Review by jschoombee — APPROVED** [review]

**Comment by mjuarez** [comment]
@jschoombee What is the release cycle/process? When can I pull this change from registry?

**Comment by jschoombee** [comment]
> @jschoombee What is the release cycle/process? When can I pull this change from registry?

If I can get through the housekeeping this evening, will get it released same time. Normally, once the tag is created it takes a few hours to become available in the registry.

**Comment by jschoombee** [comment]
> > @jschoombee What is the release cycle/process? When can I pull this change from registry?
> 
> If I can get through the housekeeping this evening, will get it released same time. Normally, once the tag is created it takes a few hours to become available in the registry.

The go releaser update had a breaking change. There is an open PR #223 to fix. As Axton is away, I can't merge my own PRs. Easiest would be for you to review and submit the same fix for goreleaser and then we can get this released

**Pull request merged**
