### PR TITLE
Users data source: pagination support

### LINKED ISSUE #120: Basic Acceptance Tests: data_source_users
### Description

Basic Acceptance Tests: data_source_users

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### LINKED ISSUE #121: Introduce pagination support for users data source
### Description

Relates to #96, to improve performance and reduce error rates, implement pagination support for the users data source
### Potential Terraform Configuration

```hcl
data "wiz_users" "tester" {
  search   = "john@foo.com"
  first = 100
  max_pages = 3
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jschoombee**
- added pagination support and acc tests for wiz_users
closes #120
closes #121
```
TF_ACC=1 go test ./internal/acceptance/... -v -run='TestAccDatasourceWizUsers_basic'
=== RUN   TestAccDatasourceWizUsers_basic
2023/05/01 13:39:43 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:43 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:44 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:45 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:46 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:47 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:48 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:48 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:49 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:50 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:51 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:51 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:52 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:53 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:53 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:54 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:55 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:56 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:57 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:58 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:58 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:59 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:40:00 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:40:00 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:40:01 [DEBUG] POST https://api.eu1.app.wiz.io/graphql


--- PASS: TestAccDatasourceWizUsers_basic (19.72s)
PASS
ok      wiz.io/hashicorp/terraform-provider-wiz/internal/acceptance     20.668s
```

### CODE REVIEW

**Comment by gramsa49** [comment]
Could this instead be implemented in the client package (versus the data source), such that it is extensible and applicable for all data sources that return multiple records?

Client package: https://github.com/AxtonGrams/terraform-provider-wiz/blob/main/internal/client/client.go

The intent with the client package is to abstract the API communication logic from the various data sources and resources in an effort to keep the source code for data sources and resources simple.

**Comment by jschoombee** [comment]
> Could this instead be implemented in the client package (versus the data source), such that it is extensible and applicable for all data sources that return multiple records?
> 
> Client package: https://github.com/AxtonGrams/terraform-provider-wiz/blob/main/internal/client/client.go
> 
> The intent with the client package is to abstract the API communication logic from the various data sources and resources in an effort to keep the source code for data sources and resources simple.

Sure can look at that. Perhaps a good start is a feature toggle for data sources to use pagination so changes can be phased in.

**Comment by jschoombee** [comment]
> > Could this instead be implemented in the client package (versus the data source), such that it is extensible and applicable for all data sources that return multiple records?
> > Client package: https://github.com/AxtonGrams/terraform-provider-wiz/blob/main/internal/client/client.go
> > The intent with the client package is to abstract the API communication logic from the various data sources and resources in an effort to keep the source code for data sources and resources simple.
> 
> Sure can look at that. Perhaps a good start is a feature toggle for data sources to use pagination so changes can be phased in.

The logic has been moved to the client package, with some refactoring, also tested this with the Kubernetes data source to validate reusability.

**Comment by gramsa49** [comment]
Looks good to me.  All acceptance tests passed:

```
$ make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/acceptance/... -v -count 1 -parallel 20  -timeout 180m
=== RUN   TestAccDatasourceWizUsers_basic
--- PASS: TestAccDatasourceWizUsers_basic (24.45s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestAccResourceWizAutomationRuleAwsSNS_basic
--- PASS: TestAccResourceWizAutomationRuleAwsSNS_basic (10.02s)
=== RUN   TestAccResourceWizAutomationRuleServiceNowCreateTicket_basic
--- PASS: TestAccResourceWizAutomationRuleServiceNowCreateTicket_basic (12.06s)
=== RUN   TestAccResourceWizAutomationRuleServiceNowUpdateTicket_basic
--- PASS: TestAccResourceWizAutomationRuleServiceNowUpdateTicket_basic (14.56s)
=== RUN   TestAccResourceWizIntegrationAwsSNS_basic
--- PASS: TestAccResourceWizIntegrationAwsSNS_basic (11.62s)
=== RUN   TestAccResourceWizIntegrationServiceNow_basic
--- PASS: TestAccResourceWizIntegrationServiceNow_basic (9.94s)
=== RUN   TestAccResourceWizSAMLIdp_basic
--- PASS: TestAccResourceWizSAMLIdp_basic (9.03s)
PASS
ok      wiz.io/hashicorp/terraform-provider-wiz/internal/acceptance     91.710s
```

**Comment by gramsa49** [comment]
```
TF_ACC=1 go test ./internal/acceptance/... -v -run='TestAccDatasourceWizUsers_basic'
=== RUN   TestAccDatasourceWizUsers_basic
2023/05/01 13:39:43 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:43 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:44 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:45 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:46 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:47 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:48 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:48 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:49 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:50 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:51 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:51 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:52 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:53 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:53 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:54 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:55 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:56 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:57 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:58 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:39:58 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:39:59 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:40:00 [DEBUG] POST https://auth.app.wiz.io/oauth/token
2023/05/01 13:40:00 [DEBUG] POST https://api.eu1.app.wiz.io/graphql
2023/05/01 13:40:01 [DEBUG] POST https://api.eu1.app.wiz.io/graphql


--- PASS: TestAccDatasourceWizUsers_basic (19.72s)
PASS
ok      wiz.io/hashicorp/terraform-provider-wiz/internal/acceptance     20.668s
```

**Pull request merged**
